/* SPDX-License-Identifier: GPL-3.0-only */
/* Jangada: print the web editor mock's parameter tables (TP, GP, ENG and the layout constants)
 * from the firmware's own tables, so the mock device cannot drift from params.c and the engines.
 * Built on the host with the test sources; tools/gen_editor_tables.py runs it and puts the output
 * between the "generated" markers of web/editor.html. */
#include <stdio.h>
#define main hostsim_main
#include "../tests/hostsim.c"
#undef main

static const char *const FMT[] = {"INT", "PCT", "BIPCT", "TIME", "LFOHZ", "CUTOFF", "DB", "SEMI", "ENUM", "BPM",
                                  "NOTE", "ONOFF", "OCT", "STEPS", "FILT"};

static void js_str(const char *s)
{
    putchar('"');
    for (; s && *s; s++) {
        if (*s == '"' || *s == '\\')
            putchar('\\');
        putchar(*s);
    }
    putchar('"');
}

static void desc(const param_desc_t *d)
{
    uint32_t i;
    if (!d->label) {                                 /* not used by the engine: as the mock had it */
        fputs("NONE", stdout);
        return;
    }
    fputs("D(", stdout);
    js_str(d->label);
    printf(", F.%s, %d, %d, %d", FMT[d->fmt], d->min, d->max, d->def);
    if (d->names || d->unit) {
        fputs(", ", stdout);
        if (d->names) {
            putchar('[');
            for (i = 0; i <= (uint32_t)(d->max - d->min); i++) {
                if (i)
                    fputs(", ", stdout);
                js_str(d->names[i]);
            }
            putchar(']');
        } else {
            fputs("null", stdout);
        }
        if (d->unit) {
            fputs(", ", stdout);
            js_str(d->unit);
        }
    }
    putchar(')');
}

static void list(const char *name, const param_desc_t *d, uint32_t n)
{
    uint32_t i;
    printf("  const %s = [\n", name);
    for (i = 0; i < n; i++) {
        fputs(i % 4u ? " " : "    ", stdout);
        desc(&d[i]);
        fputs(",", stdout);
        if (i % 4u == 3u || i + 1u == n)
            putchar('\n');
    }
    puts("  ];");
}

int main(void)
{
    uint32_t e, i, k;
    puts("  /* <generated by tools/gen_editor_tables.py from params.c and the engines: do not edit> */");
    puts("  const NONE = D(\"-\", F.INT, 0, 0, 0);");
    list("TP", TP, P_COUNT);
    list("GP", GP, G_COUNT);
    puts("  const P = (name, e, env = [10, 70, 90, 60], mono = 0, pat = 0) => ({ name, e, env, mono, pat });");
    puts("  const ENG = [");
    for (e = 0; e < NENGINES; e++) {
        const engine_t *en = ENGINES[e];
        fputs("    { name: ", stdout);
        js_str(en->name);
        fputs(", titles: [", stdout);
        js_str(en->page_title[0]);
        fputs(", ", stdout);
        js_str(en->page_title[1]);
        fputs("], edit: [\n      ", stdout);
        for (i = 0; i < NEDIT; i++) {
            desc(&en->edit[i]);
            fputs(i + 1u < NEDIT ? (i % 4u == 3u ? ",\n      " : ", ") : "],\n", stdout);
        }
        fputs("      presets: [", stdout);
        for (k = 0; k < en->npresets; k++) {
            const preset_t *p = &en->presets[k];
            fputs(k ? ",\n        P(" : "\n        P(", stdout);
            js_str(p->name);
            fputs(", [", stdout);
            for (i = 0; i < NEDIT; i++)
                printf("%s%d", i ? ", " : "",
                       i < 8u ? p->e[i] : p->x[i - 8u] ? p->x[i - 8u] - 1 : en->edit[i].def);
            printf("], [%u, %u, %u, %u], %u, %u)", p->env[0], p->env[1], p->env[2], p->env[3], p->mono, p->pat);
        }
        puts("] },");
    }
    puts("  ];");
    printf("  const P_COUNT = %u, G_COUNT = %u, NSTEP = %u, P_E0 = %u, NEDIT = %u, G_ENGSEL = %u, P_SLCR = %u;\n",
           P_COUNT, G_COUNT, NSTEP, P_E0, NEDIT, G_ENGSEL, P_SLCR);
    puts("  /* </generated> */");
    return 0;
}
